name: CI/CD

on:
  push:
    branches: main
    
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Build and tag Docker image
        run: |
          cd react-flask-app
          docker-compose build
          docker tag 414675159571.dkr.ecr.us-east-2.amazonaws.com/covid-dash:latest 414675159571.dkr.ecr.us-east-2.amazonaws.com/covid-dash:${{ github.sha }}
          
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 414675159571.dkr.ecr.us-east-2.amazonaws.com/covid-dash
      
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 414675159571.dkr.ecr.us-east-2.amazonaws.com/covid-dash:latest
          docker push 414675159571.dkr.ecr.us-east-2.amazonaws.com/covid-dash:${{ github.sha }}
